package org.projet.cabinet.dao; import java.sql.*; import java.time.LocalDateTime; import java.util.ArrayList; import java.util.List; import javax.servlet.ServletContext; import org.projet.cabinet.model.*;
public class BilanDao extends DaoBase {
    public BilanDao(ServletContext contexte) { super(contexte); }
    private Bilan mapperBilan(ResultSet rs) throws SQLException { Utilisateur uPatient = new Utilisateur(); uPatient.setId(rs.getInt("patient_utilisateur_id")); uPatient.setNom(rs.getString("patient_nom")); uPatient.setPrenom(rs.getString("patient_prenom")); uPatient.setEmail(rs.getString("patient_email")); uPatient.setMotDePasse(rs.getString("patient_mot_de_passe")); String rolePatientTexte = rs.getString("patient_role"); if (rolePatientTexte != null) { uPatient.setRole(RoleUtilisateur.valueOf(rolePatientTexte)); } Patient patient = new Patient(); patient.setId(rs.getInt("patient_id")); patient.setUtilisateur(uPatient); Date dateNaissanceSql = rs.getDate("date_naissance"); if (dateNaissanceSql != null) { patient.setDateNaissance(dateNaissanceSql.toLocalDate()); } patient.setTelephone(rs.getString("telephone")); Utilisateur medecin = new Utilisateur(); medecin.setId(rs.getInt("medecin_id")); medecin.setNom(rs.getString("medecin_nom")); medecin.setPrenom(rs.getString("medecin_prenom")); medecin.setEmail(rs.getString("medecin_email")); medecin.setMotDePasse(rs.getString("medecin_mot_de_passe")); String roleMedecinTexte = rs.getString("medecin_role"); if (roleMedecinTexte != null) { medecin.setRole(RoleUtilisateur.valueOf(roleMedecinTexte)); } Bilan bilan = new Bilan(); bilan.setId(rs.getInt("id")); bilan.setPatient(patient); bilan.setMedecin(medecin); bilan.setMotif(rs.getString("motif")); bilan.setObservations(rs.getString("observations")); bilan.setDiagnostic(rs.getString("diagnostic")); bilan.setTraitement(rs.getString("traitement")); Timestamp ts = rs.getTimestamp("date_bilan"); if (ts != null) { bilan.setDateBilan(ts.toLocalDateTime()); } return bilan; }
    private String selectCommun() { return "SELECT b.id, b.patient_id, b.motif, b.observations, b.diagnostic, b.traitement, b.date_bilan, p.date_naissance, p.telephone, up.id AS patient_utilisateur_id, up.nom AS patient_nom, up.prenom AS patient_prenom, up.email AS patient_email, up.mot_de_passe AS patient_mot_de_passe, up.role AS patient_role, um.id AS medecin_id, um.nom AS medecin_nom, um.prenom AS medecin_prenom, um.email AS medecin_email, um.mot_de_passe AS medecin_mot_de_passe, um.role AS medecin_role FROM bilans b JOIN patients p ON b.patient_id = p.id JOIN utilisateurs up ON p.utilisateur_id = up.id JOIN utilisateurs um ON b.medecin_id = um.id"; }
    public Bilan creer(Bilan bilan) { String sql = "INSERT INTO bilans (patient_id, medecin_id, motif, observations, diagnostic, traitement, date_bilan) VALUES (?,?,?,?,?,?,NOW())"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) { ps.setInt(1, bilan.getPatient().getId()); ps.setInt(2, bilan.getMedecin().getId()); ps.setString(3, bilan.getMotif()); ps.setString(4, bilan.getObservations()); ps.setString(5, bilan.getDiagnostic()); ps.setString(6, bilan.getTraitement()); ps.executeUpdate(); try (ResultSet rs = ps.getGeneratedKeys()) { if (rs.next()) { bilan.setId(rs.getInt(1)); } } if (bilan.getDateBilan() == null) { bilan.setDateBilan(LocalDateTime.now()); } return bilan; } catch (SQLException e) { throw new RuntimeException("Erreur lors de la création du bilan", e); } }
    public Bilan trouverParId(int id) { String sql = selectCommun() + " WHERE b.id = ?"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setInt(1, id); try (ResultSet rs = ps.executeQuery()) { if (rs.next()) { return mapperBilan(rs); } return null; } } catch (SQLException e) { throw new RuntimeException("Erreur lors de la recherche du bilan par id", e); } }
    public List<Bilan> trouverParPatientId(int patientId) { String sql = selectCommun() + " WHERE b.patient_id = ? ORDER BY b.date_bilan DESC"; List<Bilan> bilans = new ArrayList<>(); try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setInt(1, patientId); try (ResultSet rs = ps.executeQuery()) { while (rs.next()) { bilans.add(mapperBilan(rs)); } } return bilans; } catch (SQLException e) { throw new RuntimeException("Erreur lors du chargement des bilans du patient", e); } }
    public List<Bilan> trouverParMedecinId(int medecinId) { String sql = selectCommun() + " WHERE b.medecin_id = ? ORDER BY b.date_bilan DESC"; List<Bilan> bilans = new ArrayList<>(); try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setInt(1, medecinId); try (ResultSet rs = ps.executeQuery()) { while (rs.next()) { bilans.add(mapperBilan(rs)); } } return bilans; } catch (SQLException e) { throw new RuntimeException("Erreur lors du chargement des bilans du médecin", e); } }
    public List<Bilan> trouverTous() { String sql = selectCommun() + " ORDER BY b.date_bilan DESC"; List<Bilan> bilans = new ArrayList<>(); try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql); ResultSet rs = ps.executeQuery()) { while (rs.next()) { bilans.add(mapperBilan(rs)); } return bilans; } catch (SQLException e) { throw new RuntimeException("Erreur lors du chargement de tous les bilans", e); } }
    public void modifier(Bilan bilan) { String sql = "UPDATE bilans SET patient_id = ?, medecin_id = ?, motif = ?, observations = ?, diagnostic = ?, traitement = ? WHERE id = ?"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setInt(1, bilan.getPatient().getId()); ps.setInt(2, bilan.getMedecin().getId()); ps.setString(3, bilan.getMotif()); ps.setString(4, bilan.getObservations()); ps.setString(5, bilan.getDiagnostic()); ps.setString(6, bilan.getTraitement()); ps.setInt(7, bilan.getId()); ps.executeUpdate(); } catch (SQLException e) { throw new RuntimeException("Erreur lors de la modification du bilan", e); } }
    public void supprimer(int id) { String sql = "DELETE FROM bilans WHERE id = ?"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setInt(1, id); ps.executeUpdate(); } catch (SQLException e) { throw new RuntimeException("Erreur lors de la suppression du bilan", e); } }
}
