package org.projet.cabinet.dao; import java.sql.*; import java.time.LocalDate; import java.util.ArrayList; import java.util.List; import javax.servlet.ServletContext; import org.projet.cabinet.model.Patient; import org.projet.cabinet.model.Utilisateur; import org.projet.cabinet.model.RoleUtilisateur;
public class PatientDao extends DaoBase {
    public PatientDao(ServletContext contexte) { super(contexte); }
    private Patient mapperPatient(ResultSet rs) throws SQLException { Utilisateur u = new Utilisateur(); u.setId(rs.getInt("utilisateur_id")); u.setNom(rs.getString("nom")); u.setPrenom(rs.getString("prenom")); u.setEmail(rs.getString("email")); u.setMotDePasse(rs.getString("mot_de_passe")); String roleTexte = rs.getString("role"); if (roleTexte != null) { u.setRole(RoleUtilisateur.valueOf(roleTexte)); } Patient p = new Patient(); p.setId(rs.getInt("patient_id")); p.setUtilisateur(u); Date dateNaissanceSql = rs.getDate("date_naissance"); if (dateNaissanceSql != null) { p.setDateNaissance(dateNaissanceSql.toLocalDate()); } p.setTelephone(rs.getString("telephone")); return p; }
    public Patient creer(Patient patient) { String sql = "INSERT INTO patients (utilisateur_id, date_naissance, telephone) VALUES (?,?,?)"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS)) { ps.setInt(1, patient.getUtilisateur().getId()); LocalDate dateNaissance = patient.getDateNaissance(); ps.setDate(2, dateNaissance != null ? Date.valueOf(dateNaissance) : null); ps.setString(3, patient.getTelephone()); ps.executeUpdate(); try (ResultSet rs = ps.getGeneratedKeys()) { if (rs.next()) { patient.setId(rs.getInt(1)); } } return patient; } catch (SQLException e) { throw new RuntimeException("Erreur lors de la création du patient", e); } }
    public Patient trouverParId(int id) { String sql = "SELECT p.id AS patient_id, p.date_naissance, p.telephone, u.id AS utilisateur_id, u.nom, u.prenom, u.email, u.mot_de_passe, u.role FROM patients p JOIN utilisateurs u ON p.utilisateur_id = u.id WHERE p.id = ?"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setInt(1, id); try (ResultSet rs = ps.executeQuery()) { if (rs.next()) { return mapperPatient(rs); } return null; } } catch (SQLException e) { throw new RuntimeException("Erreur lors de la recherche du patient par id", e); } }
    public Patient trouverParUtilisateurId(int utilisateurId) { String sql = "SELECT p.id AS patient_id, p.date_naissance, p.telephone, u.id AS utilisateur_id, u.nom, u.prenom, u.email, u.mot_de_passe, u.role FROM patients p JOIN utilisateurs u ON p.utilisateur_id = u.id WHERE p.utilisateur_id = ?"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setInt(1, utilisateurId); try (ResultSet rs = ps.executeQuery()) { if (rs.next()) { return mapperPatient(rs); } return null; } } catch (SQLException e) { throw new RuntimeException("Erreur lors de la recherche du patient par utilisateur", e); } }
    public List<Patient> trouverTous() { String sql = "SELECT p.id AS patient_id, p.date_naissance, p.telephone, u.id AS utilisateur_id, u.nom, u.prenom, u.email, u.mot_de_passe, u.role FROM patients p JOIN utilisateurs u ON p.utilisateur_id = u.id ORDER BY u.nom, u.prenom"; List<Patient> patients = new ArrayList<>(); try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql); ResultSet rs = ps.executeQuery()) { while (rs.next()) { patients.add(mapperPatient(rs)); } return patients; } catch (SQLException e) { throw new RuntimeException("Erreur lors du chargement de tous les patients", e); } }
    public List<Patient> rechercherParNomEtDateNaissance(String nom, LocalDate dateNaissance) { String sql = "SELECT p.id AS patient_id, p.date_naissance, p.telephone, u.id AS utilisateur_id, u.nom, u.prenom, u.email, u.mot_de_passe, u.role FROM patients p JOIN utilisateurs u ON p.utilisateur_id = u.id WHERE u.nom LIKE ? AND p.date_naissance = ? ORDER BY u.nom, u.prenom"; List<Patient> patients = new ArrayList<>(); try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setString(1, nom + "%"); ps.setDate(2, Date.valueOf(dateNaissance)); try (ResultSet rs = ps.executeQuery()) { while (rs.next()) { patients.add(mapperPatient(rs)); } } return patients; } catch (SQLException e) { throw new RuntimeException("Erreur lors de la recherche de patients par nom et date de naissance", e); } }
    public void modifier(Patient patient) { String sql = "UPDATE patients SET date_naissance = ?, telephone = ? WHERE id = ?"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { LocalDate dateNaissance = patient.getDateNaissance(); ps.setDate(1, dateNaissance != null ? Date.valueOf(dateNaissance) : null); ps.setString(2, patient.getTelephone()); ps.setInt(3, patient.getId()); ps.executeUpdate(); } catch (SQLException e) { throw new RuntimeException("Erreur lors de la modification du patient", e); } }
    public void supprimer(int id) { String sql = "DELETE FROM patients WHERE id = ?"; try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql)) { ps.setInt(1, id); ps.executeUpdate(); } catch (SQLException e) { throw new RuntimeException("Erreur lors de la suppression du patient", e); } }

    /** Nombre total de patients. */
    public long compterTous() {
        String sql = "SELECT COUNT(*) FROM patients";
        try (Connection connexion = obtenirConnexion(); PreparedStatement ps = connexion.prepareStatement(sql); ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                return rs.getLong(1);
            }
            return 0L;
        } catch (SQLException e) {
            throw new RuntimeException("Erreur lors du comptage des patients", e);
        }
    }
}
